TIMEOUT 10
PROMPT 1
DEFAULT sunxi
LABEL sunxi
MENU LABEL Linux current-sunxi
KERNEL /boot/vmlinuz-6.18.24-current-sunxi
INITRD /boot/initramfs-sunxi
FDTDIR /boot/dtbs-lts
APPEND modules=loop,squashfs,sd-mod,usb-storage,mmc_block,sunxi-mmc modloop=/boot/modloop-sunxi modloop_sign=no console=ttyS0,115200 quiet
